### ISSUE TITLE
Errows thrown by ytdl aren't bubbling up

### ISSUE THREAD

**Issue by MikeDev96** [Snowflake107/discord-ytdl-core#12]
ytdl-core currently has a JSON parse issue, which when triggered crashes the app with no way of capturing it. This isn't an issue when using ytdl-core directly.

Reproduce:
Add an .on("error") event to the discord-ytdl-core stream.
Modify ytdl-core's lib/info.js file and add the following on line 63: `throw new Error("Test")`
Now run, ytdl-core should throw an error and you will see it's not captured by discord-ytdl-core.

**Comment by MikeDev96** [comment]
Version bump to fix said JSON issue would be great too :)
https://github.com/fent/node-ytdl-core/releases/tag/v3.4.1

**Comment by twlite** [comment]
I've added ytdl event forwarding, cheers 🍻

Events:
```js
["info", "progress", "abort", "request", "response", "error", "redirect", "retry", "reconnect"]
```
