### ISSUE TITLE
Error: input stream: This video is unavailable

### ISSUE THREAD

**Issue by FredTheNoob** [Snowflake107/discord-ytdl-core#13]
Happens on a opusEncoded stream

**Comment by udit2303** [comment]
More info? Can you tell what were you trying to play?

**Comment by twlite** [comment]
@FredTheNoob it has nothing to do with `opusEncoded`. See **[ytdl#658](https://github.com/fent/node-ytdl-core/issues/658)**

**Comment by FredTheNoob** [comment]
I tried to play this video:
https://www.youtube.com/watch?v=FuFJzY10mqc&t=2s

My dispatcher looks like this:
`const stream = ytdl(song.url, {
            filter: 'audioonly',
            opusEncoded: true,
            highWaterMark: 1024 * 1024 * 10
        });`

`const dispatcher = serverQueue.connection.play(await stream, {type: 'opus'})`

**Comment by M4X1MUS07** [comment]
@FredTheNoob The video is either age / region restricted. That's why this error occurs. Only way to fix it is by using proxy service.
