### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by noxzym** [Snowflake107/discord-ytdl-core#15]
Cannot play live stream video

**Comment by udit2303** [comment]
A better explanation for this. The song plays, but only for the starting bit. After ~5seconds, it would stop playing (or recieve data), probably cause it isn't getting the data after ~5seconds. Tried using `@discord-player/downloader` and `youtube-dl`, didn't think it was gonna work and it didn't.

**Comment by twlite** [comment]
is it working properly with `ytdl-core`?

**Comment by udit2303** [comment]
> is it working properly with `ytdl-core`?

Yes, Here's what I tried
```
const ytdl = require('ytdl-core');
message.member.voice.channel.join().then(connection => {

connection.play(ytdl("https://www.youtube.com/watch?v=W35SLNSS9OU%22", {
filter: 'audio',
quality: 'highestaudio',
highWaterMark: 1 << 25
})
);
});
```
And is playing fine. Been almost 10 minutes.

**Comment by noxzym** [comment]
but ytdl-core have some songs that cannot be played

**Comment by udit2303** [comment]
> but ytdl-core have some songs that cannot be played

Well, you could wait until some fix is released or, you could use ytdl to play live streams

**Comment by zyrouge** [comment]
This might have been caused due to `audioonly` filter. Refer https://github.com/fent/node-ytdl-core/issues/732

**Comment by sakkuntyo** [comment]
I was able to solve this problem by not using audioonly.
