### ISSUE TITLE
Problem with seek option

### ISSUE THREAD

**Issue by FredTheNoob** [Snowflake107/discord-ytdl-core#17]
Hi,

I'm trying to make a seek command using this package, now when I originally play the song I do it like this:

```js
// This plays the audio
        serverQueue.connection.play(await stream, {type: 'opus', bitrate: 'auto', seek: 0})
            // if the song ends
            .on('finish', reason => {
                if (reason === 'Stream is not generating quickly enough.') console.log('Song ended.');
                else console.error("line 49 music controller, log: " + reason);
              
                serverQueue.songs.shift();
                // play the first song in the array
                this.startPlay(serverQueue.songs[0], message);
            })
            .on('error', error => {
                console.error("Lib/MusicController.js:" + error);
                message.channel.send(embeds.error(message.author, `\`${error}\``))
                queue.delete(message.guild.id);
                return;
            })
            .on('begin', error => console.error("MusicController.js Begin Error:" + error));
        // Set the default volume
        serverQueue.connection.dispatcher.setVolumeLogarithmic(serverQueue.volume / 5);
        serverQueue.textChannel.send(embeds.extended(message.author, `**Play**`, `🎶 Started playing: **${song.title}**`, `https://img.youtube.com/vi/${song.id}/mqdefault.jpg`));
```

When seeking I do the following:
```js
async seek(message, timeStamp) {
        serverQueue = queue.get(message.guild.id);

        serverQueue.connection.play(serverQueue.currentSong, {type: 'opus', bitrate: 'auto', seek: timeStamp})
    }
```

Now when I run the seek function, I can hear that the dispatcher goes a little bit into the song, but shortly dies after. How come I resolve this issue?

Regards Fred

**Comment by twlite** [comment]
your code is passing `seek` to `discord.js dispatcher` and `discord.js seek` does not work for `opus` streams. Make sure you are passing `seek` to `discord-ytdl-core`

**Comment by twlite** [comment]
Your code should look something like this:

```js
const stream = ytdl(url, {
    opusEncoded: true,
    seek: TimeInSecondsToSeek
});

connection.play(stream, { type: "opus", bitrate: "auto" });
```

**Comment by FredTheNoob** [comment]
Thank you very much, it finally works! Now I've noticed that it takes a while before the seek happens (as in there is some silence where it loads I guess?)  - Rythm for instance doesn't have this problem at all, what should I do in order for it to seek instantly? :]

**Comment by twlite** [comment]
you are `re-creating` your stream so happens

**Comment by FredTheNoob** [comment]
I see, I've attempted to save my initial stream onto the queue like so:
```js
serverQueue.currentSong = stream;
```
When I do this, I hear that the stream will skip instantly, but dies shortly after...

**Comment by FredTheNoob** [comment]
How come I access the seek options within ytdl from serverQueue.currentSong after I set it equal to the stream?
