### ISSUE TITLE
Error: Error parsing info: Unable to retrieve video metadata

### ISSUE THREAD

**Issue by darksimusial** [Snowflake107/discord-ytdl-core#22]
Module is updated

**Comment by twlite** [comment]
This error is not from `discord-ytdl-core`. You should update your `ytdl-core` module instead

**Comment by darksimusial** [comment]
ytdl-core is updated, too

**Comment by twlite** [comment]
This error has nothing to do with this library. This library works on top of `ytdl-core` and you are getting that error from `ytdl-core`

**Comment by darksimusial** [comment]
Ok
