### ISSUE TITLE
EPIPE error

### ISSUE THREAD

**Issue by EvasiveXkiller** [Snowflake107/discord-ytdl-core#23]
I keep getting this error whenever I tried to use this library
```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at PassThrough.ondata (internal/streams/readable.js:719:22)
    at PassThrough.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
Emitted 'error' event on FFmpeg instance at:
    at FFmpeg.onerror (internal/streams/readable.js:760:14)
    at FFmpeg.emit (events.js:315:20)
    at Socket.processError (C:\Users\Thunderbolt XV\Desktop\SoundWave-dev-2.0.0\node_modules\prism-media\src\core\FFmpeg.js:64:40)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4047,
  code: 'EPIPE',
  syscall: 'write'
}
```

Here is the code that is calling this package:
```js
const stream = ytdlFallBack(song.url, {
				filter: "audioonly",
				encoderArgs: ["-af", `${queue.effects ?? "dynaudnorm=f=200"}`],
				//dlChunkSize: 0,
				opusEncoded: false,
				fmt: " mp3",
				//highWaterMark: 1 << 25,
				seek: seek || 0,
			});
			setTimeout(() => {
				let currentStream = queue.connection.play(stream, {
					type: "unknown",
					highWaterMark: 1,
				});
				currentStream.setVolumeLogarithmic(volume / 200);
				queue.dispatcher = currentStream;
				currentStream.on("finish", () => {
					if (!queue.repeatMode) {
						this.emit("songEnd", {
							initMessage: queue.initMessage,
							song: song,
						});
						queue.history = song;
						queue.effects = null;
					}
					try {
						queue.songs[0].seekTime = 0;
					} catch (e) {}
					return this.mainplayer(guildID, false);
				});
			}, 200);
```

Here are the dependencies that are installed:
```json
{
    "@discordjs/opus": "^0.5.0",
    "auto-bind": "^4.0.0",
    "bufferutil": "^4.0.3",
    "discord-ytdl-core": "^5.0.2",
    "discord.js": "^12.5.3",
    "erlpack": "^0.1.3",
    "ffmpeg-static": "^4.3.0",
    "get-audio-duration": "^2.0.3",
    "get-urls": "^10.0.0",
    "libsodium-wrappers": "^0.7.9",
    "lyrics-finder": "^21.7.0",
    "node-cron": "^3.0.0",
    "readdir-enhanced": "^6.0.4",
    "slash-commands": "^1.4.0",
    "spotify-url-info": "^2.2.0",
    "utf-8-validate": "^5.0.4",
    "winston": "^3.3.3",
    "youtubei": "0.0.1-rc.14",
    "ytdl-core": "^4.5.0",
    "ytdl-core-discord": "^1.3.0",
    "ytpl": "^2.2.0",
    "ytsr": "^3.5.0",
    "zlib-sync": "^0.1.7"
  }
```

I have tried everything I can. Sometimes (very rarely) it works but most of the time it either just immediately ends or throws the said error.

Thanks in advance.

**Comment by EvasiveXkiller** [comment]
I have also tried this

```js
const stream = ytdlFallBack(song.url, {
				filter: "audioonly",
				encoderArgs: ["-af", `${queue.effects ?? "dynaudnorm=f=200"}`],
				//dlChunkSize: 0,
				opusEncoded: true,
				//fmt: " mp3",
				highWaterMark: 1 << 25,
				seek: seek || 0,
			});
```
```js
let currentStream = queue.connection.play(stream, {
					type: "opus",
					highWaterMark: 1,
					bitrate : "auto"
				});
```

But still the error is still there

**Comment by twlite** [comment]
> I have also tried this
> 
> ```js
> const stream = ytdlFallBack(song.url, {
> 				filter: "audioonly",
> 				encoderArgs: ["-af", `${queue.effects ?? "dynaudnorm=f=200"}`],
> 				//dlChunkSize: 0,
> 				opusEncoded: true,
> 				//fmt: " mp3",
> 				highWaterMark: 1 << 25,
> 				seek: seek || 0,
> 			});
> ```
> 
> ```js
> let currentStream = queue.connection.play(stream, {
> 					type: "opus",
> 					highWaterMark: 1,
> 					bitrate : "auto"
> 				});
> ```
> 
> But still the error is still there

hello, I just ran your code and it worked fine for me

**Comment by twlite** [comment]
maybe it's caused by the song you are trying to play? could you share that as well??

**Comment by EvasiveXkiller** [comment]
The song im trying to play is [this](https://www.youtube.com/watch?v=Zw2SgJXWP-4). I have also tried other songs such as [this](https://youtube.com/watch?v=pRfmrE0ToTo)

> I have also tried this
> 
> ```js
> const stream = ytdlFallBack(song.url, {
> 				filter: "audioonly",
> 				encoderArgs: ["-af", `${queue.effects ?? "dynaudnorm=f=200"}`],
> 				//dlChunkSize: 0,
> 				opusEncoded: true,
> 				//fmt: " mp3",
> 				highWaterMark: 1 << 25,
> 				seek: seek || 0,
> 			});
> ```
> 
> ```js
> let currentStream = queue.connection.play(stream, {
> 					type: "opus",
> 					highWaterMark: 1,
> 					bitrate : "auto"
> 				});
> ```
> 
> But still the error is still there

With this code the EPIPE error is gone but the player just immediately stops and nothing is played, (`songEnd` emitted)

I have removed most of the code and tried, and i noticed that the first time that the `ytdlFallBack` method is called the dispatcher immediately emits the `end` event. The dispatcher only plays normally after the method is called again. This problem happens for every single connection to each of the server.

**Comment by twlite** [comment]
# first song
![image](https://user-images.githubusercontent.com/46562212/117229133-2199dd00-ae3a-11eb-8796-344ecce70b16.png)


and the second link is working for me

**Comment by EvasiveXkiller** [comment]
I think the first video is somehow region restricted as for me I can both open in YouTube and `ytdl-core-discord`.

I have discovered that the playing and immediately stopping is solved with just removing the `-af` switch and its parameters. After that it works as usual. It seems like having other encoderArgs such as `-ss` works with no issues.

The current working code looks like this:
```js
stream = ytdlEffectEngine(song.url, {
                    filter: "audioonly",
                    encoderArgs: ["-ss", `${seek || 0}`],
                    //seek: seek || 0,
                    //dlChunkSize: 0,
                    opusEncoded: true,
                    //highWaterMark: 1 << 25,
                })
```
